version: '3'

services:
  techblog:
    build:
      dockerfile: Dockerfile.build
      context: .
    command: jekyll serve --future
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
